###
GET http://localhost:3000/posts/all

###
GET http://localhost:3000/posts/all?owner=Tal

###
GET http://localhost:3000/posts/676476aafb3073b5e50c1f7c

###
PUT http://localhost:3000/posts/update/676476aafb3073b5e50c1f7c
content-type: application/json

{
  "title": "Hello world",
  "owner": "Tal",
  "content": "Hello World."
}

###
POST http://localhost:3000/posts/add 
content-type: application/json

{
  "title": "Hello",
  "owner": "Tal",
  "content": "Hello World..."
}


### comments ###
PUT http://localhost:3000/posts/addComment/6958f0fcc85b6a206ea5b765
content-type: application/json

{
  "username": "Tal",
  "content": "Great success"
}

###
GET http://localhost:3000/posts/comment/6766f2c6eef5996317a605c2

###
PUT http://localhost:3000/posts/comment/update/67670b61b6a476e022174af1
content-type: application/json

{
  "username": "Tal",
  "content": "Even greater success"
}

###
DELETE http://localhost:3000/posts/comment/delete/6958f128c85b6a206ea5b769

###
GET http://localhost:3000/posts/getComments/6958f0fcc85b6a206ea5b765